version: "3.1"
services:
    db:
        container_name: mysql_academia
        build: 
            context: .
            dockerfile: Dockerfile_db
        ports: 
            - "9000:3306"
        environment:
            MYSQL_DATABASE: academia
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        container_name: www_academia
        build: 
            context: .
            dockerfile: Dockerfile_www
        ports: 
            - "8003:80"
        links:
            - db
        networks:
            - default
    phpmyadmin:
        container_name: phpmyadmin_academia
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8004:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
volumes:
    persistent:
