version: "3.1"
services:
    mysql_academia:
        container_name: mysql_academia
        build: 
            context: .
            dockerfile: Dockerfile_db
        image: academia-db
        ports: 
            - "9001:3306"
        environment:
            MYSQL_DATABASE: academia
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - academia_db_data:/var/lib/mysql
        networks:
            - default
        mem_limit: 512m
    www_academia:
        container_name: www_academia
        build: 
            context: .
            dockerfile: Dockerfile_www
        image: academia-www
        #volumes:
        #    - ./www:/var/www/html
        ports: 
            - "8005:80"
        links:
            - mysql_academia
        networks:
            - default
    phpmyadmin_academia:
        container_name: phpmyadmin_academia
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql_academia:db
        ports:
            - 8006:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
volumes:
    academia_db_data: 
