version: "3.1"
services:
    db:
        container_name: mysql_academia
        build: 
            context: .
            dockerfile: Dockerfile_db
        ports: 
            - "9000:3306"
        environment:
            MYSQL_DATABASE: academia
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - academia_db_data:/var/lib/mysql
        networks:
            - default
        mem_limit: 512m
    www:
        container_name: www_academia
        build: 
            context: .
            dockerfile: Dockerfile_www
        #volumes:
        #    - ./www:/var/www/html
        ports: 
            - "8002:80"
        links:
            - db
        networks:
            - default
    phpmyadmin:
        container_name: phpmyadmin_academia
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8003:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
volumes:
    academia_db_data: 
